[package]
description = "Clockwork networking protocol"
documentation = "https://docs.clockwork.xyz"
edition = "2021"
homepage = "https://clockwork.xyz"
keywords = ["solana"]
license = "AGPL-3.0-or-later"
name = "clockwork-network-program"
readme = "./README.md"
repository = "https://github.com/clockwork-xyz/clockwork"
version = "2.0.19"

[lib]
crate-type = ["cdylib", "lib"]
name = "clockwork_network_program"

[features]
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
no-entrypoint = []
no-log-ix-name = []

[dependencies]
anchor-lang = "0.31.0"
anchor-spl = {version = "0.31.0", features = ["mint", "token"]}
clockwork-utils = {path = "../../utils", version = "=2.0.19"}
toml_datetime = "=0.6.8"
